# Copyright (c) 2021 The CapableVMs "CHERI Examples" Contributors.
# SPDX-License-Identifier: MIT OR Apache-2.0

include ../../build/Makefile.vars.riscv64-purecap
include ../../build/Makefile.vars.common
include build/Makefile.leak-capability
