# Copyright (c) 2022 The CapableVMs "CHERI Examples" Contributors.
# SPDX-License-Identifier: MIT OR Apache-2.0

SHARED_SOURCES := $(wildcard *.S) $(wildcard *.S)
HFILES := $(wildcard ../include/*.h) $(wildcard ../../../include/*.h) $(wildcard ../../../../include/*.h)
ROOTDIR=../../../..

include $(ROOTDIR)/build/Makefile.vars.morello-hybrid
include $(ROOTDIR)/build/Makefile.vars.common
include $(ROOTDIR)/build/Makefile.simple
