# Copyright (c) 2021 The CapableVMs "CHERI Examples" Contributors.
# SPDX-License-Identifier: MIT OR Apache-2.0

SHARED_SOURCES := shared.s
CFILES := $(wildcard *.c)

include ../../build/Makefile.vars.morello-hybrid
include ../../build/Makefile.vars.common
include ../../build/Makefile.simple
