# Copyright (c) 2024 The CapableVMs "CHERI Examples" Contributors.
# SPDX-License-Identifier: MIT OR Apache-2.0

include ../build/Makefile.vars.morello-purecap
include ../build/Makefile.vars.common

SHARED_SOURCES := impls.s
RUNDIR := c64-secure
export

include ../build/Makefile.simple
